# Generated by Django 4.1.7 on 2023-03-08 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(default='', max_length=50)),
                ('bio', models.TextField()),
                ('books', models.ManyToManyField(related_name='books', to='book.book')),
            ],
        ),
    ]
