# Generated by Django 4.1.7 on 2023-03-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_genre_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Art', 'art'), ("Children's", 'childrens'), ('Classic', 'Classic'), ('Science Fiction', 'science-fiction'), ('Thriller', 'thriller'), ('Biography', 'biography'), ('Christian', 'christian'), ('Science', 'science'), ('Self Help', 'self-help')], default='Art', max_length=40),
        ),
    ]
