# Generated by Django 4.1.7 on 2023-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('art', 'Art'), ('childrens', "Children's"), ('classic', 'Classic'), ('science-fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('christian', 'Christian'), ('science', 'Science'), ('self-help', 'Self Help')], default='art', max_length=40),
        ),
    ]
